name: release-bot

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
    branches:
      - master

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: reimagined/github-actions/release-pr-bot@release-actions
        with:
          event: ${{ toJSON(github.event) }}
          token: ${{ secrets.RESOLVE_BOT_PAT }}
          required_reviews: '2'
