name: release-bot

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - master*

  pull_request_review:
    types:
      - submitted
      - dismissed
      - edited
    branches:
      - master*

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: reimagined/github-actions/release-pr-bot@feature/release-action
        with:
          event: ${{ toJSON(github.event) }}
          token: ${{ secrets.RESOLVE_BOT_PAT }}
          required_reviews: 1
